# Generated by Django 4.2 on 2023-04-21 12:01

from django.db import migrations, models
import django.db.models.deletion
import social_network.models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=social_network.models.create_image_path
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="social_network.post",
                    ),
                ),
            ],
        ),
    ]
