# Generated by Django 4.2 on 2023-04-23 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_network", "0004_comment_created_at_comment_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"default_related_name": "comments"},
        ),
        migrations.AlterField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
