# Generated by Django 4.2 on 2023-04-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(upload_to="profiles/None"),
        ),
    ]
